### ISSUE TITLE
Error running tutorial notebook

### ISSUE THREAD

**Issue by flaclad** [seung-lab/torchfields#10]
I'm trying to run the notebook tutorial,
installing an importing works fine but when I run the first cell I'm getting this error 
torch.Field.ones(1, 2, 6, 6)
----
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    697                 type_pprinters=self.type_printers,
    698                 deferred_pprinters=self.deferred_printers)
--> 699             printer.pretty(obj)
    700             printer.flush()
    701             return stream.getvalue()

6 frames
/usr/local/lib/python3.7/dist-packages/torchfields/utils.py in f_decorated(*args, **kwargs)
     25         @wraps(f)
     26         def f_decorated(*args, **kwargs):
---> 27             out = f(*args, **kwargs)
     28             try:
     29                 if not isinstance(out, cls) and isinstance(out, cls.__bases__):

TypeError: __torch_function__() takes from 3 to 5 positional arguments but 6 were given

I'm trying with both pytorch1.9.0 and 1.7.0

**Comment by nkemnitz** [comment]
The pip package hasn't been updated in a while. I'll try to find somebody who has access to PyPI...

In the meantime, you can replace the first line in the tutorial with `!pip install git+https://github.com/seung-lab/torchfields.git` to get the latest version from the main branch here.

**Comment by nkemnitz** [comment]
PyPI has been updated to 0.0.6. I confirmed that the tutorial now pulls the most recent version.
